### ISSUE TITLE
VISUAL BUG WITH SHADOW AND LIGHT SKIN

### ISSUE THREAD

**Issue by Shadowinplay** [Benik/BenikUI#18]
Hey, there seems to be a minor visual bug with the BenikUI skin for Shadow and Light addon, there's an inner shadow between the Location Panel frame and the embed coordinate frame. If you could take a look, I'd appreciate.

Screenshot taken with skin enabled:
![WoWScrnShot_110222_105159](https://user-images.githubusercontent.com/111493171/199508345-5762f7fe-63fd-4da8-896a-ec3dbe555c7d.jpg)

Screenshot taken with skin disabled:
![WoWScrnShot_110222_105300](https://user-images.githubusercontent.com/111493171/199508323-54b831d4-81fe-4278-9263-acda540e3a5c.jpg)

**Comment by Benik** [comment]
Yes, it doesn't look good :)
It has to do with shadow overlapping, since each frame has BenikUI style, therefore shadow on each of them. In LocationPlus and LocationLite I add a small gap between the frames, so the shadow applies with no issue. Not sure if this can be applied in the S&L version. Will take a look at it.

**Comment by Benik** [comment]
It will look like this:
![image](https://user-images.githubusercontent.com/1357633/200003652-34678df9-1906-4957-8542-3cc28a78dd7f.png)
I will push an update in a couple of days.

**Comment by Shadowinplay** [comment]
Wonderful, thank you!

________________________________
